### ISSUE TITLE
Auto refresh on Github site

### ISSUE THREAD

**Issue by DeadLyBro** [ixrock/XTranslate#56]
It automatically refreshes the page when I switch between files or anything.

**Comment by ixrock** [comment]
Thanks for report! Gonna be fixed in next release soonish.

**Comment by DeadLyBro** [comment]
> Thanks for report! Gonna be fixed in next release soonish.

Thanks for your consideration!

**Comment by DeadLyBro** [comment]
Dude you said fixed but i don't think so. 
I removed extension and reinstalled again but issue still continue... 
I also tried refresh page after reinstall extension.

If i disable XTranslate extension, its not refreshing.

@ixrock

**Comment by ixrock** [comment]
> Dude you said fixed but i don't think so. I removed extension and reinstalled again but issue still continue... I also tried refresh page after reinstall extension.
> 
> If i disable XTranslate extension, its not refreshing.

@DeadLyBro see the commit above. It's fixed in **v.2.73.1+**

This is happened because when I noticed your issue **v.2.73.0** was already submitted to the store for review and it's not possible to cancel it while current upload reviewed. New update already submitted again.
